import 'bootstrap';
import "./equipment";
import './renderGallery.js'
import './renderItem.js'
import '../scss/index.scss';
import '../scss/equipment.scss';
import '../scss/lightbox.scss'
import '../img/IMG_3933.jpg';
import '../img/IMG_3951.jpg';
import '../img/IMG_3936e.jpg';
import '../img/IMG_3947.jpg';
import '../img/tin-can-phone.jpg'